<a href="https://colab.research.google.com/github/dab31415/SPS-Bridge-Math/blob/main/Math_HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Math HW2<br>
Donald Butler<br>
08/01/2021

In [148]:
import sympy as sp
import numpy as np

##Write a Python program to compute the eigenvalues and right eigenvectors of a given square array.

In [159]:


C = sp.randMatrix(3,3,0,10)


#lamda = sp.Symbol('lamda')
#B = C - lamda * sp.Identity(3)
#B.shape
#
#det = sp.expand(B[0,0] * (B[1,1]*B[2,2]-B[1,2]*B[2,1]) - B[0,1] * (B[1,0]*B[2,2]-B[1,2]*B[2,0]) + B[0,2] * (B[1,0]*B[2,1]-B[1,1]*B[2,0]))
#sp.factor(det,lamda)




ValueError: ignored

##Write a Python program to compute the factor of a given array by Singular Value Decomposition.

##Write a Python program to compute the determinant of an array.

In [150]:
#import numpy as np

def myDet(A):
  rows, cols = A.shape

  if rows != cols:
    return 'matrix is not square'

  if cols == 1:
    return A[0,0]
  elif cols == 2:
    return A[0,0] * A[1,1] - A[1,0] * A[0,1]
  else:
    det = 0
    for i in range(cols):
      if i % 2 == 0:
        det += A[0,i] * myDet(np.bmat([A[1:,0:i],A[1:,i+1:]]))
      else:
        det -= A[0,i] * myDet(np.bmat([A[1:,0:i],A[1:,i+1:]]))
    return det

A = np.matrix(np.random.randint(0,10,(2,3)))
print(A)
print('determinant = {0}'.format(myDet(A)))
print()

A = np.matrix(np.random.randint(0,10,(1,1)))
print(A)
print('determinant = {0}'.format(myDet(A)))
print()

A = np.matrix(np.random.randint(0,10,(2,2)))
print(A)
print('determinant = {0}'.format(myDet(A)))
print()

A = np.matrix(np.random.randint(0,10,(3,3)))
print(A)
print('determinant = {0}'.format(myDet(A)))
print()

A = np.matrix(np.random.randint(0,10,(4,4)))
print(A)
print('determinant = {0}'.format(myDet(A)))
print()


[[6 2 1]
 [7 1 1]]
determinant = matrix is not square

[[0]]
determinant = 0

[[2 5]
 [5 3]]
determinant = -19

[[0 1 0]
 [4 8 1]
 [5 2 1]]
determinant = 1

[[4 7 8 9]
 [9 6 8 1]
 [3 2 1 0]
 [0 9 9 1]]
determinant = -1087

