<a href="https://colab.research.google.com/github/dab31415/SPS-Bridge-Math/blob/main/Math_HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Math HW2<br>
Donald Butler<br>
08/01/2021

In [2]:
import sympy as sp
import numpy as np

##Write a Python program to compute the eigenvalues and right eigenvectors of a given square array.

In [93]:


A = sp.Matrix([[1,2,3],[4,5,6],[7,8,9]])
lamda = sp.Symbol('lamda')
B = A - lamda * sp.Identity(3)
# tried to use the myDet function, but generated error Mix of Matrix and Scalar symbols
# det = myDet(B)

# tried using sympy determinat function, but it didn't evaluate the lamda
# sp.det(B)

# this calcualtion works, but only allows 3x3 matrix
det = sp.expand(B[0,0] * (B[1,1]*B[2,2]-B[1,2]*B[2,1]) - B[0,1] * (B[1,0]*B[2,2]-B[1,2]*B[2,0]) + B[0,2] * (B[1,0]*B[2,1]-B[1,1]*B[2,0]))
print(det)
eigenvalues = np.roots([-1,15,18,0])
print(eigenvalues)



-lamda**3 + 15*lamda**2 + 18*lamda
[16.11684397 -1.11684397  0.        ]


##Write a Python program to compute the factor of a given array by Singular Value Decomposition.

In [ ]:
# no idea what were asked to do here. 

##Write a Python program to compute the determinant of an array.

In [91]:
def myDet(A):
  rows, cols = A.shape

  if rows != cols:
    return 'matrix is not square'

  if cols == 1:
    return A[0,0]
  elif cols == 2:
    return A[0,0] * A[1,1] - A[1,0] * A[0,1]
  else:
    det = 0
    for col in range(cols):
      # generate submatrix
      subA = np.hstack((A[1:,0:col],A[1:,col+1:]))

      # alternate signs
      if col % 2 == 0:
        det += A[0,col] * myDet(subA)
      else:
        det -= A[0,col] * myDet(subA)
    return det

A = np.matrix(np.random.randint(0,10,(2,3)))
print(A)
print('determinant = {0}'.format(myDet(A)))
print()

A = np.matrix(np.random.randint(0,10,(1,1)))
print(A)
print('determinant = {0}'.format(myDet(A)))
print()

A = np.matrix(np.random.randint(0,10,(2,2)))
print(A)
print('determinant = {0}'.format(myDet(A)))
print()

A = np.matrix(np.random.randint(0,10,(3,3)))
print(A)
print('determinant = {0}'.format(myDet(A)))
print()

A = np.matrix(np.random.randint(0,10,(4,4)))
print(A)
print('determinant = {0}'.format(myDet(A)))
print()


[[9 1 0]
 [5 4 6]]
determinant = matrix is not square

[[2]]
determinant = 2

[[5 5]
 [4 3]]
determinant = -5

[[2 3 0]
 [2 6 4]
 [0 6 2]]
determinant = -36

[[7 6 0 7]
 [9 8 7 4]
 [8 4 9 8]
 [4 7 3 1]]
determinant = 951

